appName: eximchain
developer: can kisagun
email: cankisagun@gmail.com
appURL: asdf.com
repo: ''
apiURL: 'http://strato-dev2.blockapps.net'
transferGasLimit: '21000'
contractGasLimit: '10000000'
gasPrice: '50000000000'
